# Serverless Config for Local Development

service: serverless-aws-cdk-stack

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: go1.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:us-east-1:*:*

functions:
  hello:
    handler: src/lambdas/hello/main.go
    events:
      - http:
          path: graphql
          method: any
